### ISSUE TITLE
linting test fails

### ISSUE THREAD

**Issue by donvipre** [while-true-do/ansible-role-docker-collabora#5]
### Type of Report

bug

### Actual behaviour

```
playbook: tests/test.yml
*** Linting ***
Examining test.yml of type playbook
WARNING: Couldn't open test.yml - No such file or directory
```

### Expected behaviour

Path to tests.yml should be correct.

**Comment by daniel-schier** [comment]
this is also part of the new testing suite ;)

So, I think there is not much effort needed from your side
